FROM asdlokj1qpi23/subconverter
WORKDIR /base
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del --purge tzdata && \
    rm -f /base/pref.example.*
COPY pref.* /base/
