name: "docker build"

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'  # 每小时执行一次
env:
  PROJECT: subconverter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch the latest tag from Docker Hub
        id: fetch_tag
        run: |
          latest_tag=$(curl -s https://registry.hub.docker.com/v1/repositories/asdlokj1qpi23/subconverter/tags | jq -r '.[-1].name')
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV

      - name: Check if the latest tag is new
        id: check_tag
        run: |
          echo "last_built_tag=$(cat .last_built_tag)" || echo "last_built_tag="
          if [ "${{ env.latest_tag }}" != "${last_built_tag}" ]; then
            echo "New tag found: ${{ env.latest_tag }}"
            echo "new_tag=true" >> $GITHUB_ENV
          else
            echo "No new tag found"
            echo "new_tag=false" >> $GITHUB_ENV

      - name: Set tag
        if: env.new_tag == 'true'
        id: tag
        run: |
          echo "tag=${{ env.latest_tag }}" >> $GITHUB_ENV

      - name: Set up QEMU
        if: env.new_tag == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.new_tag == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub and Sync README
        if: env.new_tag == 'true'
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        if: env.new_tag == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}:${{ env.tag }}

      - name: Sync README.md to Docker Hub
        if: env.new_tag == 'true'
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT }}
          readme: ./README.md

      - name: Save the latest tag
        if: env.new_tag == 'true'
        run: |
          echo "${{ env.latest_tag }}" > .last_built_tag
          git config --global user.email "your-email@example.com"
          git config --global user.name "github-actions"
          git add .last_built_tag
          git commit -m "Update last built tag to ${{ env.latest_tag }}"
          git push
